apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
{{ toYaml .Values.pvc.accessModes | indent 4 }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

