FROM confluentinc/cp-kafka-connect:7.5.0

USER root
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.17 \
    && confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4

USER appuser
