namespace:
  name: recsys-dataflow
images:
  zookeeper: confluentinc/cp-zookeeper:7.5.0
  kafka: confluentinc/cp-kafka:7.5.0
  pullPolicy: IfNotPresent
kafka:
  name: kafka
  bootstrapServers: kafka:29092
  topicPartitions: 4
realtimeFlinkConsumer:
  topic: cdc.behavior_events
