apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: recsys-analytics-airflow-runner
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: recsys-analytics-airflow-runner
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.airflow.serviceAccount }}
    namespace: {{ .Values.airflow.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: recsys-analytics-airflow-runner

