{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: recsys-analytics-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ANALYTICS_CATALOG_USER: {{ .Values.catalog.user | quote }}
  ANALYTICS_CATALOG_PASSWORD: {{ .Values.catalog.password | quote }}
  ANALYTICS_CATALOG_JDBC_URI: {{ printf "jdbc:postgresql://recsys-analytics-catalog-postgres:5432/%s" .Values.catalog.database | quote }}
  CATALOG_POSTGRES_DB: {{ .Values.catalog.database | quote }}
  CATALOG_POSTGRES_USER: {{ .Values.catalog.user | quote }}
  CATALOG_POSTGRES_PASSWORD: {{ .Values.catalog.password | quote }}
  SUPERSET_DATABASE_USER: {{ .Values.superset.databaseUser | quote }}
  SUPERSET_DATABASE_PASSWORD: {{ .Values.superset.databasePassword | quote }}
  SUPERSET_DATABASE_NAME: {{ .Values.superset.database | quote }}
  SUPERSET_SECRET_KEY: {{ .Values.superset.secretKey | quote }}
  SUPERSET_ADMIN_USERNAME: {{ .Values.superset.adminUser | quote }}
  SUPERSET_ADMIN_PASSWORD: {{ .Values.superset.adminPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.objectStorage.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.objectStorage.secretKey | quote }}
  MINIO_ROOT_USER: {{ .Values.objectStorage.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.objectStorage.secretKey | quote }}
{{- end }}
