{{- if .Values.istio.enabled }}
{{- if has "recsys-dataflow" .Values.istio.namespaces }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-dataflow-allow
  namespace: recsys-dataflow
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/recsys-dataflow/sa/default
              - cluster.local/ns/datahub/sa/datahub-app-sa
              - cluster.local/ns/kubeflow/sa/pipeline-runner
              - cluster.local/ns/kubeflow/sa/default
              - cluster.local/ns/observability/sa/recsys-prometheus
      to:
        - operation:
            ports: ["2181", "5432", "6121", "6122", "6123", "6124", "6125", "6379", "8081", "8083", "8088", "9000", "9091", "29092"]
    - from:
        - source:
            principals:
              - cluster.local/ns/api-serving/sa/default
      to:
        - operation:
            ports: ["5432", "6379"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-dataflow-minio-s3-allow
  namespace: recsys-dataflow
spec:
  selector:
    matchLabels:
      app: data-platform-minio
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["9000"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-dataflow-feature-postgres-allow
  namespace: recsys-dataflow
spec:
  selector:
    matchLabels:
      app: feature-postgres
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["5432"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-dataflow-redis-allow
  namespace: recsys-dataflow
spec:
  selector:
    matchLabels:
      app: redis
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["6379"]
{{- end }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-kubeflow-allow
  namespace: kubeflow
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - kubeflow
        - source:
            principals:
              - cluster.local/ns/recsys-dataflow/sa/default
              - cluster.local/ns/observability/sa/recsys-prometheus
      to:
        - operation:
            ports: ["80", "3306", "6379", "8000", "8080", "8265", "8887", "8888", "9000", "10001", "10002"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-kubeflow-ml-pipeline-api-allow
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["8887", "8888"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-kubeflow-metadata-grpc-allow
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      component: metadata-grpc-server
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["8080"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-kubeflow-seaweedfs-allow
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: seaweedfs
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["9000"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-mlflow-allow
  namespace: experiment-tracking
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/kubeflow/sa/pipeline-runner
              - cluster.local/ns/kubeflow/sa/default
              - cluster.local/ns/kubeflow/sa/default-editor
              - cluster.local/ns/kserve-triton-inference/sa/recsys-kserve-minio
              - cluster.local/ns/observability/sa/recsys-prometheus
      to:
        - operation:
            ports: ["5000", "5432", "9000"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-kserve-allow
  namespace: kserve-triton-inference
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/api-serving/sa/default
              - cluster.local/ns/observability/sa/recsys-prometheus
      to:
        - operation:
            ports: ["80", "8080", "9000"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-api-allow
  namespace: api-serving
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/ingress-nginx/sa/ingress-nginx
              - cluster.local/ns/observability/sa/recsys-prometheus
              - cluster.local/ns/api-serving/sa/default
              - cluster.local/ns/recsys-dataflow/sa/default
      to:
        - operation:
            ports: ["80", "8080"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-observability-allow
  namespace: observability
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/recsys-dataflow/sa/default
              - cluster.local/ns/api-serving/sa/default
              - cluster.local/ns/kubeflow/sa/pipeline-runner
              - cluster.local/ns/kubeflow/sa/default
              - cluster.local/ns/observability/sa/default
              - cluster.local/ns/observability/sa/recsys-prometheus
              - cluster.local/ns/observability/sa/recsys-promtail
              - cluster.local/ns/ingress-nginx/sa/ingress-nginx
      to:
        - operation:
            ports: ["3000", "3100", "3200", "4317", "9090", "9091", "9121", "9187"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-prometheus-keda-allow
  namespace: observability
spec:
  selector:
    matchLabels:
      app: recsys-prometheus
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["9090"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-loki-ingest-allow
  namespace: observability
spec:
  selector:
    matchLabels:
      app: recsys-loki
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["3100"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: recsys-tempo-otlp-allow
  namespace: observability
spec:
  selector:
    matchLabels:
      app: recsys-tempo
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["4317", "4318"]
{{- end }}
