{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    {{- if eq .Values.secretStore.provider "kubernetes" }}
    kubernetes:
      remoteNamespace: {{ .Values.secretStore.kubernetes.remoteNamespace | quote }}
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ .Values.secretStore.kubernetes.remoteNamespace | quote }}
      auth:
        serviceAccount:
          name: {{ .Values.secretStore.kubernetes.auth.serviceAccount.name }}
          namespace: {{ .Values.secretStore.kubernetes.auth.serviceAccount.namespace }}
    {{- else }}
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.mountPath | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.mountPath | quote }}
          role: {{ .Values.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.auth.serviceAccount.name }}
            namespace: {{ .Values.vault.auth.serviceAccount.namespace }}
    {{- end }}
{{- end }}
