vault:
  server: http://vault.vault.svc.cluster.local:8200
  mountPath: recsys
  auth:
    mountPath: kubernetes
    role: recsys-external-secrets
    serviceAccount:
      name: external-secrets
      namespace: external-secrets

secretStore:
  enabled: true
  provider: vault
  name: recsys-vault
  kubernetes:
    remoteNamespace: external-secrets
    auth:
      serviceAccount:
        name: external-secrets
        namespace: external-secrets

externalSecrets:
  enabled: true
  refreshInterval: 1h
  creationPolicy: Owner
  dataPlatform:
    namespace: recsys-dataflow
    secretName: recsys-data-platform-secret
    vaultPath: data-platform
  dataPlatformObservability:
    namespace: observability
    secretName: recsys-data-platform-secret
    vaultPath: data-platform
  mlflow:
    namespace: experiment-tracking
    secretName: recsys-mlflow-secrets
    vaultPath: mlflow
  runtime:
    namespace: kubeflow
    secretName: recsys-mlops-runtime
    vaultPath: runtime
    additionalVaultPaths: []
  kserve:
    namespace: kserve-triton-inference
    secretName: recsys-kserve-minio
    vaultPath: kserve-minio
    annotations:
      serving.kserve.io/s3-endpoint: minio.experiment-tracking.svc.cluster.local:9000
      serving.kserve.io/s3-usehttps: "0"
      serving.kserve.io/s3-region: us-east-1
      serving.kserve.io/s3-useanoncredential: "false"
  gateway:
    namespace: api-serving
    secretName: recsys-gateway-basic-auth
    vaultPath: gateway
  gatewayObservability:
    namespace: observability
    secretName: recsys-gateway-basic-auth
    vaultPath: gateway

istio:
  enabled: true
  namespaces:
    - kubeflow
    - experiment-tracking
    - kserve-triton-inference
    - api-serving
    - observability
