kserve:
  resources:
    requests: {cpu: 400m, memory: 2Gi}
    limits: {cpu: "2", memory: 4Gi}
  servingRuntime:
    resources:
      requests: {cpu: 400m, memory: 2Gi}
      limits: {cpu: "2", memory: 4Gi}
  sharedMemory: {sizeLimit: 512Mi}
autoscaling:
  kserveResource:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    pollingInterval: 15
    cooldownPeriod: 240
    cpu: {enabled: true, metricType: Utilization, value: "35"}
