apiVersion: batch/v1
kind: Job
metadata:
  name: init-data-platform-minio
  namespace: {{ .Values.namespace.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      enableServiceLinks: false
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: {{ .Values.images.minioClient }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          envFrom:
            - configMapRef:
                name: recsys-data-platform-config
            - secretRef:
                name: recsys-data-platform-secret
          command: ["/bin/sh", "-c"]
          args:
            - |
              until mc alias set data-platform "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                sleep 5
              done
              mc mb --ignore-existing "data-platform/{{ .Values.minio.lakeBucket }}"
              mc mb --ignore-existing "data-platform/{{ .Values.minio.offlineFeatureBucket }}"
