apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: 9000
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: 9001
  selector:
    app: {{ .Values.minio.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.minio.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: {{ .Values.minio.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.minio.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.minio.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      enableServiceLinks: false
      containers:
        - name: minio
          image: {{ .Values.images.minio }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: recsys-data-platform-secret
                  key: DATA_PLATFORM_MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recsys-data-platform-secret
                  key: DATA_PLATFORM_MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storageClassName }}
        storageClassName: {{ .Values.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.storage }}
