{{- if and .Values.auth.enabled .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Values.api.namespace }}
type: Opaque
data:
  auth: {{ .Values.auth.htpasswd | b64enc | quote }}
{{- if ne .Values.featureApi.namespace .Values.api.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Values.featureApi.namespace }}
type: Opaque
data:
  auth: {{ .Values.auth.htpasswd | b64enc | quote }}
{{- end }}
{{- if and (ne .Values.grafana.namespace .Values.api.namespace) (ne .Values.grafana.namespace .Values.featureApi.namespace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Values.grafana.namespace }}
type: Opaque
data:
  auth: {{ .Values.auth.htpasswd | b64enc | quote }}
{{- end }}
{{- if and (ne .Values.logs.namespace .Values.api.namespace) (ne .Values.logs.namespace .Values.featureApi.namespace) (ne .Values.logs.namespace .Values.grafana.namespace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Values.logs.namespace }}
type: Opaque
data:
  auth: {{ .Values.auth.htpasswd | b64enc | quote }}
{{- end }}
{{- if and (ne .Values.traces.namespace .Values.api.namespace) (ne .Values.traces.namespace .Values.featureApi.namespace) (ne .Values.traces.namespace .Values.grafana.namespace) (ne .Values.traces.namespace .Values.logs.namespace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Values.traces.namespace }}
type: Opaque
data:
  auth: {{ .Values.auth.htpasswd | b64enc | quote }}
{{- end }}
{{- end }}
