storageClassName: standard-rwo

minio:
  storage: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 1Gi

postgres:
  storage: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi

mlflow:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
