apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  FEAST_REPO_PATH: {{ .Values.config.feastRepoPath | quote }}
  FEAST_RUNTIME_REPO_PATH: {{ .Values.config.feastRuntimeRepoPath | quote }}
  FEAST_REDIS_CONNECTION_STRING: "{{ .Values.config.redisHost }}:{{ .Values.config.redisPort }}"
  FEAST_APPLY_ON_STARTUP: {{ .Values.config.feastApplyOnStartup | quote }}
  FEAST_POSTGRES_HOST: {{ .Values.config.feastPostgresHost | quote }}
  FEAST_POSTGRES_PORT: {{ .Values.config.feastPostgresPort | quote }}
  FEAST_POSTGRES_DB: {{ .Values.config.feastPostgresDatabase | quote }}
  FEAST_POSTGRES_SCHEMA: {{ .Values.config.feastPostgresSchema | quote }}
  FEAST_POSTGRES_SSLMODE: {{ .Values.config.feastPostgresSslmode | quote }}
  FEATURE_API_WARMUP_ON_STARTUP: {{ .Values.config.warmupOnStartup | quote }}
  FORCE_NOT_READY: {{ .Values.config.forceNotReady | quote }}
  ALLOW_FEATURE_FALLBACK: {{ .Values.config.allowFeatureFallback | quote }}
  RECSYS_JSON_LOGS: {{ .Values.config.jsonLogs | quote }}
  RECSYS_OTEL_ENABLED: {{ .Values.config.otelEnabled | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
  RECSYS_API_COMPONENT: online-feature-api
