apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-registry
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  FEAST_POSTGRES_USER: {{ .Values.config.feastPostgresUser | quote }}
  FEAST_POSTGRES_PASSWORD: {{ .Values.config.feastPostgresPassword | quote }}
