{{- if and .Values.kserve.enabled .Values.kserve.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kserve.secret.name }}
  namespace: {{ .Values.kserve.namespace.name }}
  annotations:
    "helm.sh/resource-policy": keep
    serving.kserve.io/s3-endpoint: {{ .Values.kserve.secret.minioEndpoint | quote }}
    serving.kserve.io/s3-usehttps: {{ .Values.kserve.secret.minioUseHttps | quote }}
    serving.kserve.io/s3-region: {{ .Values.kserve.secret.minioRegion | quote }}
    serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.kserve.secret.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.kserve.secret.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.kserve.secret.minioRegion | quote }}
  AWS_ENDPOINT_URL: {{ printf "http://%s" .Values.kserve.secret.minioEndpoint | quote }}
  S3_ENDPOINT: {{ .Values.kserve.secret.minioEndpoint | quote }}
  S3_USE_HTTPS: {{ .Values.kserve.secret.minioUseHttps | quote }}
{{- end }}
