{{- if .Values.kserve.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kserve.serviceAccount.name }}
  namespace: {{ .Values.kserve.namespace.name }}
  annotations:
    "helm.sh/resource-policy": keep
    serving.kserve.io/s3-endpoint: {{ .Values.kserve.secret.minioEndpoint | quote }}
    serving.kserve.io/s3-usehttps: {{ .Values.kserve.secret.minioUseHttps | quote }}
    serving.kserve.io/s3-region: {{ .Values.kserve.secret.minioRegion | quote }}
    serving.kserve.io/s3-useanoncredential: "false"
secrets:
  - name: {{ .Values.kserve.secret.name }}
{{- end }}
