{{- if and .Values.kserve.enabled .Values.kserve.servingRuntime.create }}
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: {{ .Values.kserve.servingRuntime.name }}
  annotations:
    "helm.sh/resource-policy": keep
    serving.kserve.io/server-type: tritonserver
spec:
  annotations:
    prometheus.kserve.io/port: "8002"
    prometheus.kserve.io/path: /metrics
  supportedModelFormats:
    - name: triton
      version: "2"
      autoSelect: true
      priority: 10
    - name: onnx
      version: "1"
      autoSelect: true
      priority: 10
  protocolVersions:
    - v2
    - grpc-v2
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 256Mi
  containers:
    - name: kserve-container
      image: {{ .Values.kserve.servingRuntime.image }}
      ports:
        - containerPort: 8080
          name: h2c
          protocol: TCP
        - containerPort: 9000
          name: grpc
          protocol: TCP
      args:
        - tritonserver
        - --model-store=/mnt/models
        - --grpc-port=9000
        - --http-port=8080
        - --allow-grpc=true
        - --allow-http=true
      startupProbe:
        httpGet:
          path: /v2/health/ready
          port: h2c
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 60
      readinessProbe:
        httpGet:
          path: /v2/health/ready
          port: h2c
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /v2/health/live
          port: h2c
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 3
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        privileged: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      resources:
{{ toYaml .Values.kserve.servingRuntime.resources | indent 8 }}
{{- end }}
