apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: minio
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.service.consolePort }}"
          envFrom:
            - secretRef:
                name: recsys-mlflow-secrets
{{- with .Values.minio.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.minio.service.apiPort }}
            - name: console
              containerPort: {{ .Values.minio.service.consolePort }}
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: api
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
